👷 allow uppercase names in archive workflow

diff --git a/.github/workflows/archive-report.yml b/.github/workflows/archive-report.yml
--- a/.github/workflows/archive-report.yml
+++ b/.github/workflows/archive-report.yml
@@ -18,17 +18,30 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: "🚧 Test [repo_name] input with regex"
+      - name: "🚧 Test [repo_user] input with regex"
         uses: actions-ecosystem/action-regex-match@v2
-        id: regex-match
+        id: user-regex-check
         with:
-          text: ${{ github.event.inputs.repo_name }}
-          regex: '[a-z-]'
+          text: ${{ github.event.inputs.repo_user }}
+          regex: '[\w,\-]'
 
       - name: "🚫 Deny invalid snippet [repo_name] input"
-        if: ${{ steps.regex-match.outputs.match == '' }}
+        if: ${{ steps.user-regex-check.outputs.match == '' }}
         run: |
-          echo "Invalid snippet folder name"
+          echo "Invalid user folder path"
+          exit 1
+          
+      - name: "🚧 Test [repo_name] input with regex"
+        uses: actions-ecosystem/action-regex-match@v2
+        id: name-regex-check
+        with:
+          text: ${{ github.event.inputs.repo_name }}
+          regex: '[\w,\-,\_]'
+
+      - name: "🚫 Deny invalid snippet [repo_name] input"
+        if: ${{ steps.name-regex-check.outputs.match == '' }}
+        run: |
+          echo "Invalid repo name folder path"
           exit 1
 
       - name: "☁️ Check out Git Repository"
